---
jobs:
  tests:
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          pipx install cpp-coveralls
          sudo apt-get update
          sudo apt-get install -y kate extra-cmake-modules lcov
      - name: Configure
        run: >-
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -B ${{github.workspace}}/build
          --install-prefix ${{github.workspace}}/build/prefix
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --verbose --config ${{matrix.build-type}}
      - name: Install
        run: cmake --install ${{github.workspace}}/build --config ${{matrix.build-type}} --verbose
      # - name: Run tests
      #   run: ctest --test-dir ${{github.workspace}}/build/src
      # - if: ${{ matrix.build-type == 'Debug' }}
      #   name: Generate coverage information
      #   run: >-
      #     geninfo
      #     '--include=src/*'
      #     '--exclude=google*/*'
      #     --exclude=test.cpp
      #     -b ${{github.workspace}}
      #     -o coverage1.info
      #     ${{github.workspace}}/build/src/CMakeFiles/ifup-systemd-resolved-tests.dir
      # - if: ${{ matrix.build-type == 'Debug' }}
      #   name: Coveralls
      #   run: coveralls -i src -e src/specialtypes.cpp -e src/test.cpp '--exclude-lines-pattern=^\}$'
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        os: [ubuntu-24.04, ubuntu-22.04]
name: Tests
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
