jobs:
  test:
    env:
      COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1'
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: 'Install dependencies'
        run: |
          pipx install cpp-coveralls
          curl -s http://archive.neon.kde.org/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/neon-archive-keyring.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/neon-archive-keyring.gpg] http://archive.neon.kde.org/user noble main" | sudo tee /etc/apt/sources.list.d/neon.list > /dev/null
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y kf6-ktexteditor-dev extra-cmake-modules lcov
      - name: 'Configure'
        run: >-
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build-type}} -B ${{github.workspace}}/build
          --install-prefix ${{github.workspace}}/build/prefix
          -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCOVERAGE=ON
      - name: 'Build'
        run: 'cmake --build ${{github.workspace}}/build --verbose --config ${{matrix.build-type}}'
      - name: 'Install'
        run: 'cmake --install ${{github.workspace}}/build --config ${{matrix.build-type}} --verbose'
      - name: 'Upload install prefix'
        uses: 'actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a'
        with:
          if-no-files-found: 'error'
          name: 'kate-wakatime-linux-${{matrix.build-type}}'
          path: '${{github.workspace}}/build/prefix'
      - env:
          QT_QPA_PLATFORM: 'offscreen'
          QT_QUICK_BACKEND: 'software'
        name: 'Run tests'
        run: 'ctest -VV --test-dir ${{github.workspace}}/build/src'
      - if: "${{ matrix.build-type == 'Debug' }}"
        name: 'Generate coverage information'
        run: >-
          geninfo
          --keep-going
          -b ${{github.workspace}}
          -o coverage1.lcov
          --exclude 'build/*'
          --exclude 'src/autotests/*'
          --exclude 'usr/*'
          ${{github.workspace}}/build
      - if: "${{ matrix.build-type == 'Debug' }}"
        name: 'Coveralls'
        uses: 'coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329'
    strategy:
      fail-fast: false
      matrix:
        build-type:
          - 'Debug'
          - 'Release'
name: 'Tests'
'on':
  pull_request:
    branches:
      - 'master'
    paths:
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cpp'
      - '**/*.cxx'
      - '**/*.h'
      - '**/*.hh'
      - '**/*.hpp'
      - '**/*.hxx'
      - '.github/workflows/tests.yml'
  push:
    branches:
      - 'master'
    paths:
      - '**/*.c'
      - '**/*.cc'
      - '**/*.cpp'
      - '**/*.cxx'
      - '**/*.h'
      - '**/*.hh'
      - '**/*.hpp'
      - '**/*.hxx'
      - '.github/workflows/tests.yml'
permissions:
  contents: 'read'
